name: Job Outputs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      job_info: "My Job Info"
    steps:
      - name: Initial Job
        run: echo "Initial Job Start"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "deployment job"
        run: |
          echo "deployment"
          echo "your info ${{needs.build.outputs.job_info}}"
