name: Run Composite Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Job
        run: echo "Initial Job Start"

      - name: Run Composite Action
        uses: mehrabhossaindev/simpleCompositeActionWithOutPram@main

      - name: Run Composite Action with Param
        uses: mehrabhossaindev/simpleCompositeActionWithPram@main
        with:
          nodeJsVersion: 23
