name: Build vue project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm Install
        run: echo "Npm Install"
        
      - name: npm run build
        run: echo "Npm run build"
        

      

  
  
  
